// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distSqrToSeg
double distSqrToSeg(NumericVector u, NumericVector v0, NumericVector v1);
RcppExport SEXP _DEEBesti_distSqrToSeg(SEXP uSEXP, SEXP v0SEXP, SEXP v1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v1(v1SEXP);
    rcpp_result_gen = Rcpp::wrap(distSqrToSeg(u, v0, v1));
    return rcpp_result_gen;
END_RCPP
}
// distSqrToPwLin
NumericVector distSqrToPwLin(NumericMatrix path, NumericVector query);
RcppExport SEXP _DEEBesti_distSqrToPwLin(SEXP pathSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type path(pathSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(distSqrToPwLin(path, query));
    return rcpp_result_gen;
END_RCPP
}
// whichMinDistToPwLin
double whichMinDistToPwLin(NumericMatrix path, NumericVector id, NumericVector query);
RcppExport SEXP _DEEBesti_whichMinDistToPwLin(SEXP pathSEXP, SEXP idSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type path(pathSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(whichMinDistToPwLin(path, id, query));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DEEBesti_distSqrToSeg", (DL_FUNC) &_DEEBesti_distSqrToSeg, 3},
    {"_DEEBesti_distSqrToPwLin", (DL_FUNC) &_DEEBesti_distSqrToPwLin, 2},
    {"_DEEBesti_whichMinDistToPwLin", (DL_FUNC) &_DEEBesti_whichMinDistToPwLin, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DEEBesti(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
