// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distSqrToSeg
double distSqrToSeg(NumericVector u, NumericVector v0, NumericVector v1);
RcppExport SEXP _DEEBesti_distSqrToSeg(SEXP uSEXP, SEXP v0SEXP, SEXP v1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v1(v1SEXP);
    rcpp_result_gen = Rcpp::wrap(distSqrToSeg(u, v0, v1));
    return rcpp_result_gen;
END_RCPP
}
// distSqrToPwLin
NumericVector distSqrToPwLin(NumericMatrix path, NumericVector query);
RcppExport SEXP _DEEBesti_distSqrToPwLin(SEXP pathSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type path(pathSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(distSqrToPwLin(path, query));
    return rcpp_result_gen;
END_RCPP
}
// whichMinDistToPwLin
double whichMinDistToPwLin(NumericMatrix path, NumericVector id, NumericVector query);
RcppExport SEXP _DEEBesti_whichMinDistToPwLin(SEXP pathSEXP, SEXP idSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type path(pathSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(whichMinDistToPwLin(path, id, query));
    return rcpp_result_gen;
END_RCPP
}
// expKernelMatrix
NumericMatrix expKernelMatrix(NumericMatrix state, double bandwidth, double regulation);
RcppExport SEXP _DEEBesti_expKernelMatrix(SEXP stateSEXP, SEXP bandwidthSEXP, SEXP regulationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type state(stateSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< double >::type regulation(regulationSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelMatrix(state, bandwidth, regulation));
    return rcpp_result_gen;
END_RCPP
}
// expKernelVector
NumericVector expKernelVector(NumericVector xout, NumericMatrix x, double bandwidth);
RcppExport SEXP _DEEBesti_expKernelVector(SEXP xoutSEXP, SEXP xSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelVector(xout, x, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelVectors
NumericMatrix expKernelVectors(NumericMatrix xout, NumericMatrix x, double bandwidth);
RcppExport SEXP _DEEBesti_expKernelVectors(SEXP xoutSEXP, SEXP xSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelVectors(xout, x, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelDerivVector
NumericMatrix expKernelDerivVector(NumericVector xout, NumericMatrix x, double bandwidth);
RcppExport SEXP _DEEBesti_expKernelDerivVector(SEXP xoutSEXP, SEXP xSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelDerivVector(xout, x, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelVectorFromDistSqr
NumericVector expKernelVectorFromDistSqr(NumericVector distSqr, double bandwidth);
RcppExport SEXP _DEEBesti_expKernelVectorFromDistSqr(SEXP distSqrSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type distSqr(distSqrSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelVectorFromDistSqr(distSqr, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelMatrix1D
NumericMatrix expKernelMatrix1D(NumericVector x, double bandwidth, double regulation);
RcppExport SEXP _DEEBesti_expKernelMatrix1D(SEXP xSEXP, SEXP bandwidthSEXP, SEXP regulationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< double >::type regulation(regulationSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelMatrix1D(x, bandwidth, regulation));
    return rcpp_result_gen;
END_RCPP
}
// expKernelVectors1D
NumericMatrix expKernelVectors1D(NumericVector x, NumericVector xout, double bandwidth);
RcppExport SEXP _DEEBesti_expKernelVectors1D(SEXP xSEXP, SEXP xoutSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelVectors1D(x, xout, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// expKernelDerivVectors1D
NumericMatrix expKernelDerivVectors1D(NumericVector x, NumericVector xout, double bandwidth);
RcppExport SEXP _DEEBesti_expKernelDerivVectors1D(SEXP xSEXP, SEXP xoutSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(expKernelDerivVectors1D(x, xout, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// whichMinDist
int whichMinDist(NumericMatrix x, NumericVector y);
RcppExport SEXP _DEEBesti_whichMinDist(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(whichMinDist(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distToVec
NumericVector distToVec(NumericMatrix x, NumericVector y);
RcppExport SEXP _DEEBesti_distToVec(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(distToVec(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distSqrToVec
NumericVector distSqrToVec(NumericMatrix target, NumericVector query);
RcppExport SEXP _DEEBesti_distSqrToVec(SEXP targetSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type target(targetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(distSqrToVec(target, query));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DEEBesti_distSqrToSeg", (DL_FUNC) &_DEEBesti_distSqrToSeg, 3},
    {"_DEEBesti_distSqrToPwLin", (DL_FUNC) &_DEEBesti_distSqrToPwLin, 2},
    {"_DEEBesti_whichMinDistToPwLin", (DL_FUNC) &_DEEBesti_whichMinDistToPwLin, 3},
    {"_DEEBesti_expKernelMatrix", (DL_FUNC) &_DEEBesti_expKernelMatrix, 3},
    {"_DEEBesti_expKernelVector", (DL_FUNC) &_DEEBesti_expKernelVector, 3},
    {"_DEEBesti_expKernelVectors", (DL_FUNC) &_DEEBesti_expKernelVectors, 3},
    {"_DEEBesti_expKernelDerivVector", (DL_FUNC) &_DEEBesti_expKernelDerivVector, 3},
    {"_DEEBesti_expKernelVectorFromDistSqr", (DL_FUNC) &_DEEBesti_expKernelVectorFromDistSqr, 2},
    {"_DEEBesti_expKernelMatrix1D", (DL_FUNC) &_DEEBesti_expKernelMatrix1D, 3},
    {"_DEEBesti_expKernelVectors1D", (DL_FUNC) &_DEEBesti_expKernelVectors1D, 3},
    {"_DEEBesti_expKernelDerivVectors1D", (DL_FUNC) &_DEEBesti_expKernelDerivVectors1D, 3},
    {"_DEEBesti_whichMinDist", (DL_FUNC) &_DEEBesti_whichMinDist, 2},
    {"_DEEBesti_distToVec", (DL_FUNC) &_DEEBesti_distToVec, 2},
    {"_DEEBesti_distSqrToVec", (DL_FUNC) &_DEEBesti_distSqrToVec, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DEEBesti(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
