# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distSqrToSeg <- function(u, v0, v1) {
    .Call(`_NonParamODE_distSqrToSeg`, u, v0, v1)
}

distSqrToPwLin <- function(path, query) {
    .Call(`_NonParamODE_distSqrToPwLin`, path, query)
}

whichMinDistToPwLin <- function(path, query) {
    .Call(`_NonParamODE_whichMinDistToPwLin`, path, query)
}

whichMinDist <- function(x, y) {
    .Call(`_NonParamODE_whichMinDist`, x, y)
}

distToVec <- function(x, y) {
    .Call(`_NonParamODE_distToVec`, x, y)
}

